CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    country VARCHAR(255) NOT NULL
);